# Generated by Django 4.2.6 on 2024-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(max_length=400),
        ),
    ]
