# Generated by Django 4.2.6 on 2024-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_course_image_url_alter_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='work_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
