# Generated by Django 4.2.6 on 2024-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_place_description_alter_place_page_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='page_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
