# Generated by Django 4.2.6 on 2024-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='naver_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
